---

- name: Prepare CloudInit configuration
  hosts: localhost
  gather_facts: no
  tags:
    - cloudinit_prepare
    - cloudinit

  tasks:

    - name: Create ssh key pair directory
      file:
        path: "{{ vm_ssh_key_path | dirname }}"
        state: directory

    - name: Create ansible ssh key pair
      community.crypto.openssh_keypair:
        path: "{{ vm_ssh_key_path }}"
        type: "{{ vm_ssh_key_type }}"
        comment: "{{ vm_ssh_comment }}"

    - name: Create CloudInit config
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../templates/cloud_init.yml.j2"
        dest: "{{ playbook_dir }}/../../../terraform/config/cloud_init.yml"
        mode: "0664"
